language: python
cache:
    directories:
        - $HOME/.cache/pip # same as pip
        - $HOME/.poetry
        - $HOME/.cache/pypoetry
        - $TRAVIS_BUILD_DIR/.venv
python:
    - 3.8
before_install:
    # Setup deploy key (https://gist.github.com/qoomon/c57b0dc866221d91704ffef25d41adcf)
    - >-
        openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv -in github_deploy_key.enc -out github_deploy_key -d
    - chmod 600 github_deploy_key
    - eval $(ssh-agent -s)
    - ssh-add github_deploy_key
    # Get Poetry
    - travis_retry curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > /tmp/get-poetry.py
    - travis_retry python /tmp/get-poetry.py --preview --yes
    - source $HOME/.poetry/env
install:
    - travis_retry poetry install
script:
    - poetry run pytest
    - poetry run sphinx-build docs ./genDocs
deploy:
    - provider: pypi
      distributions: sdist bdist_wheel
      user: rgoswami
      password:
          secure: aZKdTal0sag7njO8UKyf+tix2n17KmnXwFgbtkdD9ycGvStxeVtwHt58uQynuWZ8SW/CgaAaBA2Nnfl7nQSGrCkkMo+Xfc/PYQFbkEz5GvJOAfK6ShaGsofXtu+kwqIU6CO0XKX4IPLJ51UQj8ICg+TZLigb19J8FPcf5XCpidVPIuenphj9I8NVw02v2ni9bbANIzJCB3kApu60if+r/2JGELzx7DISq4BSFzxlEPfeZWQKo6T6EoH+eh+j0jTfppws1+m2cVNhvD4IzBpQbGFmxEV+EErB4YJChmfmw1Fnx4AOECJ9aPn/K7KgDMirjJl9ojMFkM/w5i7xK/iTuyPFy8yx11C4dGOSqFSsnmF1ooV9MhTCuoxHqFJHpspNQ4fo7F8Nwi7uDy8sGSa89o7hXngIvuh4DkTOdY826IqoeB8EP7NFEialFoPB7lCWOJLbof6kA1O+VcRDKrtuKhorbN2YNbauymp4verWB1B2JqM7CMqGrXSp4EbYcx5b6RVSrzJeiAWOSMFHIogOHBEFjzSEyC5+fsDjnOHNLxV6QyHh/bBTeFQcFt641UHQuFou7uNR0HReOHf4oQf07Mtsn53IZxk0KmhVyyHEaXw/qq0YNwtpqtAyYLNUghHZor3/PNtFWCz3j1aJ46J4eOz4tEdv0LBwws2Pkzu2gBc=
      on:
          tags: true
          repo: HaoZeke/wailord
          python: 3.8

    - provider: pages
      local_dir: ./genDocs
      skip_cleanup: true
      keep_history: true
      target_branch: pages
      on:
          branch: main
