site_name: wailord
site_description: A Python library for working with ORCA
site_author: Rohit Goswami

repo_url: https://github.com/HaoZeke/wailord
edit_uri: https://github.com/HaoZeke/wailord/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
