[project]
name = "wailord"
version = "0.1.0"
description = "An ORCA helper"
authors = ["Rohit Goswami <rog32@hi.is>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
pip = "23.3.1.*"
python = ">=3.12.*"
pdm = "2.10.1.*"
