[tool]
[tool.poetry]
name = "wailord"
version = "0.0.1"
description = "Wailord is a python library to interact with ORCA"
license = "GNU General Public License v3"
keywords = ["wailord"]
classifiers = ["Development Status :: 2 - Pre-Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: GNU General Public License v3 (GPLv3)", "Natural Language :: English", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.5", "Programming Language :: Python :: 3.6", "Programming Language :: Python :: 3.7", "Programming Language :: Python :: 3.8"]
homepage = "https://github.com/HaoZeke/wailord"
authors = ["Rohit Goswami <rog32@hi.is>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "*"
click = ">=7.0"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
