import wailord.io as waio
import filecmp
import difflib
import sys


def test_xyz(datadir):
    sx = waio.xyz.xyzIO(datadir / "h2mol.xyz")
    assert sx.comment_line == "XYZ file generated by Avogadro.\n"
    sx.comment_line = "new"
    assert sx.comment_line == "new"
    pass


def printDiff(f1, f2):
    """
    Helper function to diagnose errors between files
    """
    with open(f1) as fo1:
        f1t = fo1.read()
    with open(f2) as fo2:
        f2t = fo2.read()
    res = difflib.unified_diff(f1t, f2t)
    sys.stdout.writelines(res)
    pass


def test_write_xyz(tmp_path, datadir):
    """
    The write test
    """
    d = tmp_path / "xyz"
    d.mkdir()
    orig = datadir / "h2mol.xyz"
    testout = d / "t.xyz"
    sx = waio.xyz.xyzIO(orig)
    sx.write(testout)
    res = filecmp.cmp(orig, testout)
    if res == False:
        printDiff(orig, testout)
    assert res == True
    pass


def test_slugxyz(datadir):
    sx = waio.xyz.xyzIO(datadir / "h2mol.xyz")
    assert sx.slug == "H2_h2mol"
    pass


def test_sysxyz(datadir):
    sx = waio.xyz.xyzIO(datadir / "h2mol.xyz")
    assert sx.system == "H2"
    pass


def test_counts(datadir):
    sx = waio.xyz.xyzIO(datadir / "h2mol.xyz")
    assert sx.counts == {"H": 2}
    pass
