# -*- coding: utf-8 -*-
"""XYZ helpers for the batch shell.

Parsing and structured frames live in **chemparseplot** (grammar track).
This module only provides thin conveniences used by multi-job ORCA harness
generation (coordinate blocks for ``.inp`` embedding).
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any


def parse_xyz(path_or_text: str | Path) -> Any:
    """Parse XYZ via ``chemparseplot.api.parse_xyz`` (requires grammar track).

    Accepts a path or raw XYZ text. Prefer this over any wailord-local parser.
    """
    from chemparseplot.api import parse_xyz as _parse

    if isinstance(path_or_text, Path):
        return _parse(str(path_or_text))
    return _parse(path_or_text)


def coord_block(path: str | Path) -> str:
    """Atom lines only (no natoms/comment), spaced for ORCA ``* xyz`` blocks.

    Reads the file textually so harness generation does not require the grammar
    extra; symbols/coords are taken from lines after the two-line XYZ header.
    """
    lines = Path(path).read_text().splitlines()
    body = lines[2:] if len(lines) > 2 else []
    out: list[str] = []
    for aline in body:
        each = aline.split()
        if each:
            out.append("    ".join(each))
    return "\n".join(out)


def atom_symbols(path: str | Path) -> list[str]:
    """Element symbols from an XYZ file (order preserved)."""
    lines = Path(path).read_text().splitlines()
    body = lines[2:] if len(lines) > 2 else []
    symbols: list[str] = []
    for aline in body:
        each = aline.split()
        if each:
            symbols.append(each[0])
    return symbols


def system_label(path: str | Path) -> str:
    """Compact composition label (e.g. ``H2``) from atom counts."""
    counts = Counter(atom_symbols(path))
    parts: list[str] = []
    for sym, n in counts.items():
        parts.append(str(sym))
        parts.append(str(n))
    return "".join(parts)


def write_xyz(
    path: str | Path,
    *,
    symbols: list[str],
    coordinates: list[tuple[float, float, float]],
    comment: str = "Generated by wailord",
) -> None:
    """Write a plain XYZ file (batch harness helper)."""
    comment = comment.rstrip("\n")
    lines = [str(len(symbols)), comment]
    for sym, (x, y, z) in zip(symbols, coordinates, strict=True):
        lines.append(f"{sym} {x} {y} {z}")
    Path(path).write_text("\n".join(lines) + "\n")


def rewrite_xyz(src: str | Path, dest: str | Path) -> None:
    """Byte-preserving copy helper for harness staging."""
    Path(dest).write_bytes(Path(src).read_bytes())
