name: "Build & Test"
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.12]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          cache-dependency-path: |
              ./pdm.lock
              ./pdm.new.lock
      - name: Install dependencies
        run: pdm install -G:all
      - name: Test project
        run: pdm run pytest
