name: "Upload"
on: [push, pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.0, 1.1.2]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Prep dependencies
        run: poetry add twine && poetry install
      - name: Test project
        run: poetry run pytest
      - name: Build project
        run: poetry build
      - name: Publish distribution 📦 to Test PyPI
        if: matrix.python-version == '3.9' && startsWith(github.ref, 'refs/heads/main')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: poetry run twine upload --non-interactive -r testpypi dist/*
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry run twine upload --non-interactive -r pypi dist/*
